# alacritty-windows.toml
[general]
import = ["~/GH/dotfiles/alacritty/alacritty.toml"]

[terminal.shell]
program = "C:\\Program Files\\Git\\bin\\bash.exe"
args = ["-l"]

[env]
TERM = "xterm-256color"
